# Generated by Django 4.2.2 on 2023-06-26 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=59)),
            ],
        ),
        migrations.CreateModel(
            name='BibTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BibEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date added')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliography.author')),
                ('tags', models.ManyToManyField(to='bibliography.bibtag')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
